spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres-user:5432/user_db
    username: user_user
    password: user_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

  redis:
    host: redis
    port: 6379
    timeout: 2000ms

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:dev-secret-key-change-in-production-minimum-256-bits}
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
  issuer: stock-management-auth-service

logging:
  level:
    root: INFO
    com.stock.authservice: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
